spring.application.name=ProyectoTareas

server.port=8080

#ORACLE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=TareasProyecto
spring.datasource.password=TareasProyecto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ORACLE DIALECT
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# LOGS
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.cors=DEBUG
